name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Deploy to Firebase
        run: /
          npm install -g firebase-tools
          npm install
          npm run test
          npm run build
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
