name: Deploy to Firebase

on:
  push:
    branches:
      - master

jobs:
  deploy_to_firebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1

      - name: Install packages
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Deploy to Firebase
        run: npm run deploy
